import '../app/styles/globals.css'
import NavBar from "./components/Nav.jsx"
import Provider from './components/Provider'
export const metadata = {
  title: 'Prompt Topia',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
 
      <body>
        <Provider>
               <div className='main '>
                 <div  className='gradient'/>

               </div>
              <div>
              <main className='app'>
                 <NavBar/>
               {children}
               </main>
              </div>
        </Provider>
      </body>
    </html>
  )
}
